run:
  deadline: 1m
  issues-exit-code: 1
  skip-files:
    - "^.*_easyjson.go$"

output:
  format: colored-line-number

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100

linters:
  enable-all: true
