// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package icqbotapi

import (
	json "encoding/json"
	event "github.com/bm0/icq-bot-api/event"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB24b5487DecodeGithubComBm0IcqBotApi(in *jlexer.Lexer, out *PollResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "events":
			if in.IsNull() {
				in.Skip()
				out.Events = nil
			} else {
				in.Delim('[')
				if out.Events == nil {
					if !in.IsDelim(']') {
						out.Events = make([]event.Event, 0, 1)
					} else {
						out.Events = []event.Event{}
					}
				} else {
					out.Events = (out.Events)[:0]
				}
				for !in.IsDelim(']') {
					var v1 event.Event
					(v1).UnmarshalEasyJSON(in)
					out.Events = append(out.Events, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB24b5487EncodeGithubComBm0IcqBotApi(out *jwriter.Writer, in PollResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"events\":"
		out.RawString(prefix[1:])
		if in.Events == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Events {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PollResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB24b5487EncodeGithubComBm0IcqBotApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PollResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB24b5487EncodeGithubComBm0IcqBotApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PollResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB24b5487DecodeGithubComBm0IcqBotApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PollResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB24b5487DecodeGithubComBm0IcqBotApi(l, v)
}
